const SEM_PISTA: &str = "(Sem pista.)";

pub const LIVRO_1: [&str; 80] = [
    "Earl Akintern tem constantes dores de cabeça.",
    "A faca no peito de Foster não foi enfiada por mãos humanas.",
    "Pista do assassino (3 partes):\nIII) Sabor amargo.",
    "O chão da baia de Mecha Prateada tinha pingos frescos de tinta preta.",
    "Pista do motivo (4 partes):\nIII) Digo.",
    "Coronel Sebastian Moran.",
    SEM_PISTA,
    "Jules Redmarch comprou algumas pílulas para atenuar suas vertigens.",
    "Pista da arma (2 partes):\nI) Ofertar.",
    "Cuidado! Muito Cuidado, caro senhor de casaca.\n'Nitro' é pior que champanhe, pode acabar em ressaca.",
    "O duque de Lacourt é um conhecido colecionador de manuscritos originais.",
    "O sr. Foster e a sra. Walton trabalharam juntos em várias invenções.",
    "Um dos hobbies de Lars é a numismática.",
    "Reginal Cosgrove fizera um seguro valioso para seu cavalo Mecha Prateada.",
    "Segundo a pauta da reunião com Tomball, Ostermann apresentaria um relatório sobre os lucros do banco.",
    "A caixa (Pista 116) continha uma réplica do colar de Ziegfield e um bilhete, cujo texto pode ser obtido na charutaria.",
    "Pistas da surpresa (4 partes):\nI) Eu sou, tu ___, ele é.\nII) Antes de optar, analise os ___ e os contras.",
    "Pista da arma (3 partes):\nIII) Medida do tempo de vida desde o nascimento.",
    "O técnico já estava morto quando a grade de ventilação foi removida.",
    "Uma pista importante pode ser achada nas docas.",
    "Akintern foi visto lendo a Bíblia para a vitima e para o duque de Lacourt um dia antes do crime.",
    "Pista do assassino (2 partes):\nI) Que pessoa ou coisa (entre várias)?",
    "Bertram Luxwell acabou de voltar de Paris.",
    "Pista da arma (3 partes):\nI) Unha afiada e curva que as feras e aves de rapina possuem.",
    "Pista do motivo (4 partes):\nIV) Após o P.",
    "O nome verdadeiro de Jonathan Hackett pode ser obtido na farmácia.",
    "O cocheiro não é o Camaleão.",
    "Leopold Kamerly é agente secreto da Inteligência Britânica.",
    "Pista do mentor (2 partes):\nI) 3,1416.",
    "Uma pista para a identidade do criminoso está na livraria.",
    "Pista geral do motivo:\nNão se pode julgar um livro pela capa.",
    "Pista do assassino (2 partes):\nII) Altura de um som.",
    "Pista de arma (3 partes):\nI) Desloca-se velozmente.",
    "Pista do assassino (2 partes):\nI) Costura (verbo).",
    "Pista do assassino (2 partes):\nII) Membro que agarra.",
    "Coronel Sebastian Moran estuda o hipnotismo.",
    "Pista do Camaleão (2 partes):\nI) Fazes uma leitura.",
    "Você chegou aqui bem a tempo de impedir que Boris Kapril deixasse o país.",
    "Em sua viagem Picard visitou uma tribo.",
    "Dique, didique, didoque!\nDiz o relógio cantando,\nAs doze passam tranquilas,\nOlhando as treze chegando!\nDique, didique, didoque!",
    "A filha da duquesa, Katia, não gostava do estranho pregador.",
    "Um dia antes do crime, o sr. Foster e a sra. Walton foram vistos cochichando no saguão do hotel.",
    "Pista do assassino (3 partes):\nI) Aquilo que não varia.",
    "Respingos frescos de tinta cinza foram encontrados no chão da baia de Diabo Negro, outro cavalo de Reginald.",
    "Às vezes, Rita Frawley e Walter Ostermann passam a noite no hotel.",
    "Coronel Sebastian Moran é sócio do famigerado professor Moriarty.",
    "Pistas da surpresa (4 partes):\nIII) A terceira vogal.\nIV) O papagaio imita a ___ humana.",
    "Uma pipa e um longo fio de cobre foram encontrados no telhado do hotel.",
    "Pista do mentor (2 partes):\nII) Um tipo de comunicação por escrito.",
    "Uma pista sobre a arma está no bar.",
    "Pista geral da arma:\nSegundo a Bíblia, quem viver pela ___ morrerá por ela.",
    "Na cigarreira que fica na escrivaninha do quarto dos Foster, uma espécie de catapulta foi armada.",
    "Pista completa do motivo (2 partes):\nI) Já foi criança e adolescente.\nII) Relativo ao ar.",
    SEM_PISTA,
    "Pista do motivo (4 partes):\nI) Ofereça.",
    "Pistas do articulador do plano (4 partes):\nI) Tritura.\nII) Anfíbio anuro, da família dos ranídeos.",
    "Pistas do local da surpresa (4 partes):\nI) Vai ao chão, por desequilíbrio.\nII) Enxerguei.",
    "Pista do assassino (2 partes):\nII) Um mês inglês.",
    "Pista do assassino (2 partes):\nII) De minha propriedade.",
    SEM_PISTA,
    "Earl Akintern é especialista em manuscritos originais.",
    "Pistas do motivo (4 partes):\nII) Liga, junta.\nIII) Eu venho, tu vens, ele ___.",
    "O assassino é um radioamador.",
    "Pista do motivo (2 partes):\nII) Líder espiritual.",
    "Pista do motivo (4 partes):\nII) Antigo namorado.",
    "Hyman Pearson foi nomeado superintendente de segurança da Exposição Internacional de Joias do próximo fim de semana.",
    SEM_PISTA,
    "Pista do motivo (3 partes):\nIII) Linha que segue uma direção constante.",
    "Pista do esconderijo das chapas(2 partes):\nI) As chapas estão escondidas na concavidade por baixo ...\n(continua na pista II, museu).",
    "Dê uma passada na livraria.",
    "O manuscrito original de Hamlet foi roubado recentemente de uma exposição em Nice, no litoral da França.",
    SEM_PISTA,
    "Pista geral do motivo e do assassino:\nUm pequeno passarinho contou tudo para ela.",
    "Pista do motivo (2 partes):\nI) Indica condição.",
    "Durante os últimos 2 anos, Wellington Bakman vem mantendo um padrão de vida incompatível com seu salário.",
    "Pista do assassino (2 partes):\nI)Advérbio de lugar.",
    "O assassino é um homem.",
    "Pista da arma (3 partes):\nII) Embarcação a vela usada para passeio.",
    "Pista do assassino (2 partes):\nII) O oposto de agudo.",
    "Pista da arma (3 partes):\nIII) Extremidades inferiores do corpo humano."
];

pub const LIVRO_2: [&str; 1] = [
    "Os daltônicos não conseguem distinguir o verde do vermelho."
];

pub const LIVRO_3: [&str; 1] = [
    "O general Margram tinha bigodes e barba."
];