const SEM_PISTA: &str = "(Sem pista.)";

pub const LIVRO_1: [&str; 37] = [
    "Earl Akintern tem constantes dores de cabeça.",
    "A faca no peito de Foster não foi enfiada por mãos humanas.",
    "Pista do assassino (3 partes): \nIII) Sabor amargo.",
    "O chão da baia de Mecha Prateada tinha pingos frescos de tinta preta.",
    "Pista do motivo (4 partes): \nIII) Digo.",
    "Coronel Sebastian Moran.",
    SEM_PISTA,
    "Jules Redmarch comprou algumas pílulas para atenuar suas vertigens.",
    "Pista da arma (2 partes): \nI) Ofertar.",
    "Cuidado! Muito Cuidado, caro senhor de casaca. \n'Nitro' é pior que champanhe, pode acabar em ressaca.",
    "O duque de Lacourt é um conhecido colecionador de manuscritos originais.",
    "O sr. Foster e a sra. Walton trabalharam juntos em várias invenções.",
    "Um dos hobbies de Lars é a numismática.",
    "Reginal Cosgrove fizera um seguro valioso para seu cavalo Mecha Prateada.",
    "Segundo a pauta da reunião com Tomball, Ostermann apresentaria um relatório sobre os lucros do banco.",
    "A caixa (Pista 116) continha uma réplica do colar de Ziegfield e um bilhete, cujo texto pode ser obtido na churataria.",
    "Pistas da surpresa (4 partes): \nI) Eu sou, tu ___, ele é. \nII) Antes de optar, analise os ___ e os contras.",
    "Pista da arma (3 partes): \nIII) Medida do tempo de vida desde o nascimento.",
    "O técnico já estava morto quando a grade de ventilação foi removida.",
    "Uma pista importante pode ser achada nas docas.",
    "Akintern foi visto lendo a Bíblia para a vitima e para o duque de Lacourt um dia antes do crime.",
    "Pista do assassino (2 partes): \nI) Que pessoa ou coisa (entre várias)?",
    "Bertram Luxwell acabou de voltar de Paris.",
    "Pista da arma (3 partes): \nI) Unha afiada e curva que as feras e aves de rapina possuem.",
    "Pista do motivo (4 partes): \nIV) Após o P.",
    "O nome verdadeiro de Jonathan Hackett pode ser obtido na farmácia.",
    "O cocheiro não é o Camaleão.",
    "Leopold Kamerly é agente secreto da Inteligência Britânica.",
    "Pista do mentor (2 partes): \nI) 3,1416.",
    "Uma pista para a identidade do criminoso está na livraria.",
    "Pista geral do motivo: \nNão se pode julgar um livro pela capa.",
    "Pista do assassino (2 partes): \nII) Altura de um som.",
    "Pista de arma (3 partes): \nI) Desloca-se velozmente.",
    "Pista do assassino (2 partes): \nI) Costura (verbo).",
    "Pista do assassino (2 partes): \nII) Membro que agarra.",
    "Coronel Sebastian Moran estuda o hipnotismo.",
    "Pista do Camaleão (2 partes): \nI) Fazes uma leitura."
];