const SEM_PISTA: &str = "(Sem pista.)";

pub const LIVRO_1: [&str; 171] = [
    "Earl Akintern tem constantes dores de cabeça.",
    "A faca no peito de Foster não foi enfiada por mãos humanas.",
    "Pista do assassino (3 partes):\nIII) Sabor amargo.",
    "O chão da baia de Mecha Prateada tinha pingos frescos de tinta preta.",
    "Pista do motivo (4 partes):\nIII) Digo.",
    "Coronel Sebastian Moran.",
    SEM_PISTA,
    "Jules Redmarch comprou algumas pílulas para atenuar suas vertigens.",
    "Pista da arma (2 partes):\nI) Ofertar.",
    "Cuidado! Muito Cuidado,\ncaro senhor de casaca.\n'Nitro' é pior que champanhe,\npode acabar em ressaca.",
    "O duque de Lacourt é um conhecido colecionador de manuscritos originais.",
    "O sr. Foster e a sra. Walton trabalharam juntos em várias invenções.",
    "Um dos hobbies de Lars é a numismática.",
    "Reginal Cosgrove fizera um seguro valioso para seu cavalo Mecha Prateada.",
    "Segundo a pauta da reunião com Tomball, Ostermann apresentaria um relatório sobre os lucros do banco.",
    "A caixa (Pista 116) continha uma réplica do colar de Ziegfield e um bilhete, cujo texto pode ser obtido na charutaria.",
    "Pistas da surpresa (4 partes):\nI) Eu sou, tu ___, ele é.\nII) Antes de optar, analise os ___ e os contras.",
    "Pista da arma (3 partes):\nIII) Medida do tempo de vida desde o nascimento.",
    "O técnico já estava morto quando a grade de ventilação foi removida.",
    "Uma pista importante pode ser achada nas docas.",
    "Akintern foi visto lendo a Bíblia para a vitima e para o duque de Lacourt um dia antes do crime.",
    "Pista do assassino (2 partes):\nI) Que pessoa ou coisa (entre várias)?",
    "Bertram Luxwell acabou de voltar de Paris.",
    "Pista da arma (3 partes):\nI) Unha afiada e curva que as feras e aves de rapina possuem.",
    "Pista do motivo (4 partes):\nIV) Após o P.",
    "O nome verdadeiro de Jonathan Hackett pode ser obtido na farmácia.",
    "O cocheiro não é o Camaleão.",
    "Leopold Kamerly é agente secreto da Inteligência Britânica.",
    "Pista do mentor (2 partes):\nI) 3,1416.",
    "Uma pista para a identidade do criminoso está na livraria.",
    "Pista geral do motivo:\nNão se pode julgar um livro pela capa.",
    "Pista do assassino (2 partes):\nII) Altura de um som.",
    "Pista de arma (3 partes):\nI) Desloca-se velozmente.",
    "Pista do assassino (2 partes):\nI) Costura (verbo).",
    "Pista do assassino (2 partes):\nII) Membro que agarra.",
    "Coronel Sebastian Moran estuda o hipnotismo.",
    "Pista do Camaleão (2 partes):\nI) Fazes uma leitura.",
    "Você chegou aqui bem a tempo de impedir que Boris Kapril deixasse o país.",
    "Em sua viagem Picard visitou uma tribo.",
    "Dique, didique, didoque!\nDiz o relógio cantando,\nAs doze passam tranquilas,\nOlhando as treze chegando!\nDique, didique, didoque!",
    "A filha da duquesa, Katia, não gostava do estranho pregador.",
    "Um dia antes do crime, o sr. Foster e a sra. Walton foram vistos cochichando no saguão do hotel.",
    "Pista do assassino (3 partes):\nI) Aquilo que não varia.",
    "Respingos frescos de tinta cinza foram encontrados no chão da baia de Diabo Negro, outro cavalo de Reginald.",
    "Às vezes, Rita Frawley e Walter Ostermann passam a noite no hotel.",
    "Coronel Sebastian Moran é sócio do famigerado professor Moriarty.",
    "Pistas da surpresa (4 partes):\nIII) A terceira vogal.\nIV) O papagaio imita a ___ humana.",
    "Uma pipa e um longo fio de cobre foram encontrados no telhado do hotel.",
    "Pista do mentor (2 partes):\nII) Um tipo de comunicação por escrito.",
    "Uma pista sobre a arma está no bar.",
    "Pista geral da arma:\nSegundo a Bíblia, quem viver pela ___ morrerá por ela.",
    "Na cigarreira que fica na escrivaninha do quarto dos Foster, uma espécie de catapulta foi armada.",
    "Pista completa do motivo (2 partes):\nI) Já foi criança e adolescente.\nII) Relativo ao ar.",
    SEM_PISTA,
    "Pista do motivo (4 partes):\nI) Ofereça.",
    "Pistas do articulador do plano (4 partes):\nI) Tritura.\nII) Anfíbio anuro, da família dos ranídeos.",
    "Pistas do local da surpresa (4 partes):\nI) Vai ao chão, por desequilíbrio.\nII) Enxerguei.",
    "Pista do assassino (2 partes):\nII) Um mês inglês.",
    "Pista do assassino (2 partes):\nII) De minha propriedade.",
    SEM_PISTA,
    "Earl Akintern é especialista em manuscritos originais.",
    "Pistas do motivo (4 partes):\nII) Liga, junta.\nIII) Eu venho, tu vens, ele ___.",
    "O assassino é um radioamador.",
    "Pista do motivo (2 partes):\nII) Líder espiritual.",
    "Pista do motivo (4 partes):\nII) Antigo namorado.",
    "Hyman Pearson foi nomeado superintendente de segurança da Exposição Internacional de Joias do próximo fim de semana.",
    SEM_PISTA,
    "Pista do motivo (3 partes):\nIII) Linha que segue uma direção constante.",
    "Pista do esconderijo das chapas(2 partes):\nI) As chapas estão escondidas na concavidade por baixo ...\n(continua na pista II, museu).",
    "Dê uma passada na livraria.",
    "O manuscrito original de Hamlet foi roubado recentemente de uma exposição em Nice, no litoral da França.",
    SEM_PISTA,
    "Pista geral do motivo e do assassino:\nUm pequeno passarinho contou tudo para ela.",
    "Pista do motivo (2 partes):\nI) Indica condição.",
    "Durante os últimos 2 anos, Wellington Bakman vem mantendo um padrão de vida incompatível com seu salário.",
    "Pista do assassino (2 partes):\nI)Advérbio de lugar.",
    "O assassino é um homem.",
    "Pista da arma (3 partes):\nII) Embarcação a vela usada para passeio.",
    "Pista do assassino (2 partes):\nII) O oposto de agudo.",
    "Pista da arma (3 partes):\nIII) Extremidades inferiores do corpo humano.",
    "A exposição de joias deste fim de semana terá um raro acontecimento:\nA exibição do colar de Ziegfield, que tem as mais valiosas pedras preciosas do mundo num só objeto.",
    SEM_PISTA,
    "Pista do motivo (3 partes):\nII) Enxugue.",
    "O chimpanzé de Mario Morelli sabe usar um estilingue.",
    "Antes do N e depois dele\nSão do meu nome as pistas.\nDá risada por enquanto!\nDepois saberás, no entanto,\nO que fazem os artistas.",
    "O filme mostra Hyman com aparência transtornada, passando por cima dos cadáveres para remover o diamante do cofre.",
    "Pista do Camaleão (2 partes):\nII) O oposto de cedo.",
    "Um dia antes de Ladder ser morto, Redmarch foi visto no parque conversando com Boris Kapril.",
    "Pista da arma (2 partes):\nCompaixão.",
    "(Sem pistas, aqui e na charutaria.)",
    "Pista do assassino (2 partes):\nII) O que não é externo.",
    "Pistas do motivo (4 partes):\nI) Afirmação.\nIV) O que está preso num cativeiro.",
    "Pista da arma (3 partes):\nIII) Substância preta utilizada na pavimentação de ruas.",
    "O recibo de penhor encontrado na cena do crime pertencia a Reginald Cosgrove.",
    "Pista do assassino (2 partes):\nI) Ruído do choque entre dois corpos.",
    "Motivo completo:\nO plano foi tramado com a intenção de obter tanto o diamante Thomson quanto o colar de Ziegfield.",
    SEM_PISTA,
    "Pista do assassino (2 partes):\nI) Um lugar onde se descansa.",
    "Pista geral sobre a remoção das placas:\nForam levadas por mãos humanas, pelos tubos de ventilação.",
    SEM_PISTA,
    "O bispo de Whittenfronth estava no teatro na noite do crime.",
    "Na noite do crime, os FOster foram ao teatro com os Southerington.",
    SEM_PISTA,
    "Pegadas no estábulo mostram que o assassino usa sapatos tamanho 46.",
    "Pista da arma (3 partes):\nI) ___ de jabuticaba: jabuticabeira.",
    "Pistas do articulador do plano (4 partes):\nIII) Caminhava.\nIV) Obra que visa à realização de um ideal de beleza.",
    "Pistas para o local da surpresa (4 partes):\nII) Bebida tomada às 5h da tarde pelos ingleses.\nI) Diminutivo de olho.",
    "Pista da arma (3 partes):\nII) Mulher que desempenha um papel.",
    "O assassino é nativo da África.",
    "Uma pista mto importante está na farmácia.",
    SEM_PISTA,
    "O sr. Foster e a sra. Walton tinham um caso amoroso.",
    "Toshfeld comprou o relógio cuco numa recente viagem à Suíça.",
    "Pistas da arma (3 partes):\nII) O que a girafa e a alfafa têm em comum.\nIII) Não inteira; partida.",
    "Tanto Rita Frawley como Patrick Tomball são canhotos.",
    "Ao chegar em casa, voltando da casa de Sherlock Holmes, Hyman encontrou uma segunda caixa esperando por ele.\nHá Algo a respeito no banco.",
    SEM_PISTA,
    "Pista da arma (3 partes):\nI) A letra antes do M.",
    "Pista do assassino (2 partes):\nI) Porco em inglês.",
    "Quando uma champanhe é aberta,\ncausa grande emoção\nMas, neste caso, fiquei alerta\nesta pode causar uma explosão!",
    "A vítima estava com a pele bastante bronzeada, o que é incomum em Londres.",
    SEM_PISTA,
    "O legista encontrou duas pulgas mortas no pescoço da vítima.",
    "Bobby Jansen trabalha atualmente na oficina do chaveiro.",
    "A vítima estava de costas para o assassino quando foi golpeada.",
    "A Scotland Yard foi mobilizada para garantir a segurança na Exibição Internacional de Joias neste fim de semana.",
    "Lestrade estava transferindo o Camaleão para outra prisão, quando ele escapou.",
    SEM_PISTA,
    "Há um furo do diâmetro de uma agulha na base do pescoço do técnico.",
    SEM_PISTA,
    "O bispo de Whittenfronth fuma charutos cubanos.",
    "Todos os amigos sabiam que, ao acordar, e antes de fazer qualquer coisa, o sr. Foster sentia a necessidade de fumar um cigarro.",
    "Pista do assassino (3 partes):\nII) Claridade.",
    "Reginald Cosgrove janais mataria um cavalo premiado, como Mecha Prateada.",
    "Pista da arma (3 partes):\nII) Caldo.",
    "Texto do segundo bilhete (pista 16):\n'Substitua o colar de Ziegfield por esta réplica e aguarde novas instruções. Se você falhar, recomendaremos à Scotland Yard que assista aos filmes do cinetoscópio.'",
    "Pista geral do caso:\nO Camaleão conta com o fato de que Holmes fica nervoso quando toca.",
    "Pista do motivo (3 partes):\nI) Dotá-la de forma.",
    "Pista do esconderijo (2 partes):\nII) ___ de uma mesa da exposição, no museu\n(continuação da pista I, charutaria).",
    SEM_PISTA,
    "Pista para o código:\nH = I\n B = C",
    "O pedaço de vela achado por Holmes era parte de uma pesada vela decorativa(cerca de 2 kg). É razoável supor que ninguém usaria uma vela dessas só para iluminar um caminho.",
    SEM_PISTA,
    "Subkow, toma regularmente pílulas amarelas devido a crises renais.",
    "A arma e a mala foram jogadas ao mar.",
    "Pista para o código:\nK = L",
    "Pista do assassino (4 partes):\nI) O mesmo que mau.",
    "Pistas do motivo (4 partes):\nII) 2 meses era a ___ da filhinha da duquesa.\nIII) Tornou obrigatória uma condição.",
    "Enquanto esfregava o chão do banco no sábado passado, Harvey Willis, encarregado da limpeza, ouviu um barulho que vinha do escritório de arquitetura, na casa ao lado.",
    "O navio de Prescott está sendo reclamado pelo ex-dono, por falta de pagamento",
    "Pista para o código:\nZ = A\nG = H",
    "Pista completa da arma:\nI) Enxerga.\nII) Vire-se para este ___.\nIII) Enrubesce.\nIV) Não passiva.",
    "Pista do sequestrador (3 partes):\nIII) Tipo de dança muito conhecido, comum em festas de casamento.",
    "Pistas do assassino (3 partes):\nII) Oposto de sem.\nIII) Por favor em inglês.",
    "Pista da fortuna (4 partes):\nI) Décima quarta consoante do alfabeto.",
    "A mensagem contém 3 palavras.",
    "Pistas do motivo (3 partes):\nI) Após o D.\nII) Pelo de carneiro.",
    "Pista do paradeiro (3 partes):\nI) Deus do vinho na mitologia romana.",
    "Pista do assassino (3 partes):\nI) Os aqui presentes, sem exceção.",
    "Holmes notou uma marca de ferrugem entre o polegar e o indicador da mão direita do capitão Whiter.",
    "Pista para o código:\nM = N",
    "Ao contrário da esposa, que não ligava para as atividade sociais, Winston aspirava ardentemente por uma vida social intensa.",
    "Pista do sequestrador (3 partes):\nI) Doze meses.",
    "Pistas do motivo (4 partes):\nIII) Indivíduo maior e emancipado.\nIV) Incorretos.",
    "Pista do assassino:\nBranco em inglês.",
    "Pista para o código:\nS = T",
    "Pista do assassino (4 partes):\nIV) Estar por um ___.",
    "Pista do sequestrador (3 partes):\nII) Lugar do porto onde ocorrem o embarque e o desembarque.",
    "George Netter fez uma nova chave na segunda-feira.",
    "Pista da arma (2 partes):\nII) Nascida na Inglaterra.",
    "As pérolas Olhos de Lúcifer eram valiosas demais para que Hickel se separasse delas. Ele ainda estava com elas quando morreu."
];

pub const LIVRO_2: [&str; 1] = [
    "Os daltônicos não conseguem distinguir o verde do vermelho."
];

pub const LIVRO_3: [&str; 1] = [
    "O general Margram tinha bigodes e barba."
];